name: 'dart_weather'
version: 1.0.0
build: 'release'

environment:
  sdk: '^3.4.0'

dependencies:
  http: ^1.2.1
  async: ^2.11.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  meta: ^1.15.0
  path: ^1.9.0
  source_span: ^1.10.0
  string_scanner: ^1.2.0
  term_glyph: ^1.2.1
  typed_data: ^1.3.2
  web: ^0.5.1
